<script setup lang="ts"></script>
<template>
  <div class="p-6 text-center text-xl font-bold text-red-600">
    <p>
      JE BRANCHE LE CONTACT JE SUIS VIN DIESEL VOITURE VOITURRRRRREEEEEEE
      !!!!!!!! JE VROUMmmmmmmm JE VAIS À 300 À L'HEURE ET JE FAIS DES DÉRAPAGES
      COMME UN
      PROOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
      !!!!!!!! MAIS ATTENTIONNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
      JE SUIS PAS UN ENFANT JE SUIS UN PILOTE DE COURSE DE FORMULE 1 DE
      VOITURESSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
      !!!!!!!! ma femme refuse de me laisser voir les enfants
    </p>
  </div>
</template>
