services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express-vue-app
    environment:
      POSTGRES_URL: postgres://user:password@postgres:5432/mydatabase
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  postgres_data: